### ISSUE TITLE
compositionSelector

### ISSUE THREAD

**Issue by vfarcic** [TeraSky-OSS/backstage-plugins#2]
Add field to select the Composition by name in case there are multiple Compositions in a Configuration. Set the default value of that field to `spec.defaultCompositionRef.name` in `CompositeResourceDefinition` (if that field is defined).

**Comment by vrabbi** [comment]
I had considered that but thought that the label selector method was a better approach. Do you see the composition name slection as a better option or should both options be exposed?

**Comment by vrabbi** [comment]
i have changed the UX and the new version to use for the kubernetes-ingestor with this functionality is in 1.1.0. no changes in the app-config.yaml are needed, and multiple options are now available in the revamped flow. it now supports not selecting a composition and leaving the defaulting up to the cluster, specifying a specific composition from a dropdown list of the discovered compositions which implement this XRD and the third option is the label selector which is what previously existed. let me know how it works for you

**Comment by vfarcic** [comment]
I prefer using labels when writing YAML directly. However, from a Web UI, I think that composition name is a better approach since it allows selections (drop-down lists) which are not possible/practical with labels since it would be close to impossible to provide any type of a selection with more than one label.

**Comment by vrabbi** [comment]
makes sense. let me know if the new version works for you, or if anything needs further changes around this
